FROM ubuntu:bionic
# FROM arm64=arm64v8/ubuntu:bionic

ARG APT_ARCHIVE_SOURCE="archive.ubuntu.com"

RUN sed -i "s|archive.ubuntu.com|${APT_ARCHIVE_SOURCE}|" /etc/apt/sources.list \
 && apt-get update \
 && apt-get install -y \
      curl \
      git \
      wget \
      unzip

ENV DAPPER_ENV VERSION DEV_BUILD
ENV DAPPER_DOCKER_SOCKET true
ENV DAPPER_SOURCE /go/src/github.com/burmilla/os-services
ENV DAPPER_OUTPUT ./dist
ENV DAPPER_RUN_ARGS --privileged
ENV SHELL /bin/bash
WORKDIR ${DAPPER_SOURCE}

########## General Configuration #####################
ARG DAPPER_HOST_ARCH=amd64
ARG HOST_ARCH=${DAPPER_HOST_ARCH}
ARG ARCH=${HOST_ARCH}

ARG OS_REPO=burmilla
ARG DOCKER_URL_amd64=https://download.docker.com/linux/static/stable/x86_64/docker-26.1.4.tgz
ARG DOCKER_URL_arm64=https://download.docker.com/linux/static/stable/aarch64/docker-26.1.4.tgz

ARG IMAGE_BUILD_NAME=[1-9]*

######################################################

# Set up environment
ENV DOCKER_URL DOCKER_URL_${ARCH}

# Export all ARGS as ENV
ENV ARCH=${ARCH} 
ENV DISTRIB_ID=${DISTRIB_ID}
ENV DOCKER_PATCH_VERSION=${DOCKER_PATCH_VERSION}
ENV DOCKER_URL=${DOCKER_URL}
ENV DOCKER_URL_amd64=${DOCKER_URL_amd64}
ENV DOCKER_URL_arm64=${DOCKER_URL_arm64}
ENV DOCKER_URL_arm=${DOCKER_URL_arm}
ENV DOCKER_VERSION=${DOCKER_VERSION}
ENV HOST_ARCH=${HOST_ARCH}
ENV OS_REPO=${OS_REPO}

# Meaningful ENV
ENV IMAGE_BUILD_NAME=${IMAGE_BUILD_NAME}

RUN rm /bin/sh && \
    ln -s /bin/bash /bin/sh

# Install Host Docker
RUN curl -fL ${!DOCKER_URL} > /tmp/docker.tgz && \
    tar zxvf /tmp/docker.tgz --strip-components=1 -C /usr/bin/ && \
    chmod +x /usr/bin/docker

# Install dapper
RUN curl -sL https://releases.rancher.com/dapper/v0.5.4/dapper-`uname -s`-`uname -m | sed 's/arm.*/arm/'` > /usr/bin/dapper && \
    chmod +x /usr/bin/dapper

ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]
