docker-compose:
  image: ${REGISTRY_DOMAIN}/burmilla/os-dockercompose:2.8.0
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: console
    io.docker.compose.rebuild: always
  net: none
  privileged: true
  volumes_from:
  - all-volumes
