name: build-docker

on:
  push:
    branches:
      - v2.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Build Docker
      run: |
        export DOCKER_VERSION=1.10.3
        export IMAGE_BUILD_NAME="10-docker-*"
        make release

    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image(s) to Docker Hub
      run: ${PWD}/dist/publish.sh
